<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-02-24 20:02
=======
# Generated by Django 5.1.6 on 2025-02-24 20:13
>>>>>>> 7683fcb226b53d154cc843cc534baf8747ca8cc4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
