# Generated by Django 5.1.5 on 2025-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_material_arquivo_material_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
