# Generated by Django 5.1.6 on 2025-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_meumodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
