# Generated by Django 5.1.5 on 2025-01-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_material_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(default='materiais/media1.jpg', upload_to='materiais/'),
        ),
    ]
