# Generated by Django 5.1.5 on 2025-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_material_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(upload_to='materiais/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
