# Generated by Django 3.2.25 on 2025-07-26 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_materialsalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data_compartilhado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
            preserve_default=False,
        ),
    ]
