# Generated by Django 5.2.4 on 2025-07-29 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_material_data_compartilhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='data_compartilhado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
