# Generated by Django 3.2.25 on 2025-07-29 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_material_data_compartilhado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='avaliacoes_habilitadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='colaboradores_confirmados',
            field=models.ManyToManyField(blank=True, related_name='colaboracoes_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='colaboradores_pendentes',
            field=models.ManyToManyField(blank=True, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curtidas', models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.material')),
            ],
        ),
    ]
