# Generated by Django 5.2.4 on 2025-08-05 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250729_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='colaboracao_habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='materiais_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
