# Generated by Django 5.2.6 on 2025-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_historicopesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='comentarios_habilitados',
            field=models.BooleanField(default=False),
        ),
    ]
