# Generated by Django 3.2.25 on 2025-09-24 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_material_comentarios_habilitados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteColaboracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('negado', 'Negado')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos_detalhados', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
