# Generated by Django 3.2.25 on 2025-09-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_convitecolaboracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='comentarios_habilitados',
        ),
    ]
