# Generated by Django 3.2.25 on 2025-10-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_material_comentarios_habilitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando', 'Aguardando colaboração'), ('publicado', 'Publicado')], default='rascunho', max_length=20),
        ),
    ]
