# Generated by Django 5.1.6 on 2025-02-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfil_localizacao_perfil_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
